export const caseStudies = [
  {
    id:      'design-ops',
    index:   '01',
    title:   'Building a Design Operations Function from the Ground Up',
    company: 'Plexus Worldwide',
    year:    '2024',
    outcome: 'Consolidated 6 fragmented tools into a unified design system, cutting team inefficiency by 60% and increasing sprint delivery velocity by 35%.',
    tags:    ['Design Ops', 'Systems Thinking', 'Team Leadership', 'AI Tooling'],
    color:   '#C8FF00',
    href:    'https://design-ops-case-study.vercel.app/',
  },
  {
    id:      'plexus-ecomm',
    index:   '02',
    title:   'E-Commerce Modernization: From Friction to Conversion',
    company: 'Plexus Worldwide',
    year:    '2024',
    outcome: 'Redesigned the complete e-commerce experience across US and 3 international regions — reducing checkout abandonment by 43% through data-driven UX and mobile-first design.',
    tags:    ['e-Commerce', 'UX Strategy', 'Mobile-First', 'A/B Testing'],
    color:   '#FF6B35',
    href:    'https://director-case-study-ux-bgoals.vercel.app/',
  },
  {
    id:      'ux-transformation',
    index:   '03',
    title:   'Leading a Company-Wide UX Transformation',
    company: 'Multi-Company · 2021–2024',
    year:    '2021–2024',
    outcome: 'Elevated design from a service function to a strategic driver — securing C-suite buy-in and delivering measurable outcomes across e-commerce, mining, and self-storage.',
    tags:    ['UX Strategy', 'Executive Influence', 'Cross-Functional', 'Workshops'],
    color:   '#8B5CF6',
    href:    'https://company-ux-transform.vercel.app/',
  },
]
