export const caseStudies = [
  {
    id: 'design-ops',
    slug: 'design-ops',
    title: 'Building a Design Operations Function from the Ground Up',
    company: 'Plexus Worldwide',
    year: '2024',
    role: 'Principal Product Designer / Acting Design Lead',
    outcome: 'Consolidated 6 fragmented tools into a unified design system, cutting team inefficiency by 60% and increasing sprint delivery velocity by 35%.',
    shortOutcome: '60% inefficiency reduction · 35% velocity increase',
    tags: ['Design Ops', 'Systems Thinking', 'Team Leadership', 'AI Tooling'],
    color: '#C8FF00',
    href: 'https://design-ops-case-study.vercel.app/',
    external: true,
    index: '01',
  },
  {
    id: 'plexus-ecomm',
    slug: 'plexus-ecomm',
    title: 'E-Commerce Modernization: From Friction to Conversion',
    company: 'Plexus Worldwide',
    year: '2024',
    role: 'Principal Product Designer / Acting Design Lead',
    outcome: 'Redesigned the complete e-commerce experience across US and 3 international regions — reducing checkout abandonment by 43% through data-driven UX and mobile-first PDPs.',
    shortOutcome: '43% checkout abandonment reduced · 3 regions launched',
    tags: ['e-Commerce', 'UX Strategy', 'Mobile-First', 'A/B Testing'],
    color: '#FF6B35',
    href: 'https://director-case-study-ux-bgoals.vercel.app/',
    external: true,
    index: '02',
  },
  {
    id: 'ux-transformation',
    slug: 'ux-transformation',
    title: 'Leading a Company-Wide UX Transformation',
    company: 'Multi-Company · 2021–2024',
    year: '2021–2024',
    role: 'Senior Product Designer → Principal Designer',
    outcome: 'Elevated design from a service function to a strategic driver — securing C-suite buy-in, implementing design thinking processes, and delivering measurable user and business outcomes across e-commerce, mining, and self-storage verticals.',
    shortOutcome: '30% worker efficiency · 75% POS completion rate',
    tags: ['UX Strategy', 'Executive Influence', 'Cross-Functional', 'Workshop Facilitation'],
    color: '#8B5CF6',
    href: 'https://company-ux-transform.vercel.app/',
    external: true,
    index: '03',
  },
]
